/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from 'react-native';

export const Colors = {
  light: {
    background: '#F9FAFB',
    foreground: '#171717',
    accentWhite: '#ffffff',
    primary: '#050711',
    offWhite: '#F8F9FA',
    offWhite2: '#F5F6F7',
    offWhite3: '#F8F9FA',
    lightGray: '#E9ECEF',
    mediumGray: '#DEE2E6',
    slateGray: '#6C757D',
    darkSlateGray: '#495057',
    black: '#000000',
    primaryLighter: '#a3a3a4',
    primaryNormal: '#050711',
    paleMintGreen: '#D1E7DD',
    mutedSageGreen: '#6C8B7D',
    paleBlushPink: '#F8D7DA',
    mutedCoralRed: '#DC3545',
    paleCream: '#FFF3CD',
    burntOrange: '#FD7E14',
    bgPrimary: '#F8F9FA',
    bgSecondary: '#E9ECEF',
    bgTertiary: '#DEE2E6',
    textPrimary: '#050711',
    textSecondary: '#495057',
    textTertiary: '#6C757D',
    textInverse: '#F8F9FA',
    statusSuccess: '#6C8B7D',
    statusWarning: '#FD7E14',
    statusError: '#DC3545',
    statusInfo: '#6C757D',
    interactivePrimary: '#0F172A',
    interactiveSecondary: '#6C8B7D',
    interactiveHover: '#FFF3CD',
    interactiveDisabled: '#DEE2E6',
    shadowColor: '#6C8B7D',
    shadowLight: 'rgba(108, 139, 125, 0.1)',
    shadowMedium: 'rgba(108, 139, 125, 0.2)',
    shadowDark: 'rgba(108, 139, 125, 0.3)',
    text: '#050711',
    tint: '#FD7E14',
    icon: '#6C757D',
    tabIconDefault: '#6C757D',
    tabIconSelected: '#FD7E14',
  },
  dark: {
    background: '#0F172A',
    foreground: '#F1F5F9',
    accentWhite: '#1E293B',
    primary: '#F1F5F9',
    offWhite: '#1E293B',
    offWhite2: '#1E293B',
    offWhite3: '#1E293B',
    lightGray: '#334155',
    mediumGray: '#475569',
    slateGray: '#94A3B8',
    darkSlateGray: '#CBD5E1',
    black: '#F1F5F9',
    primaryLighter: '#94A3B8',
    primaryNormal: '#F1F5F9',
    paleMintGreen: '#D1E7DD',
    mutedSageGreen: '#6C8B7D',
    paleBlushPink: '#F8D7DA',
    mutedCoralRed: '#DC3545',
    paleCream: '#FFF3CD',
    burntOrange: '#FD7E14',
    bgPrimary: '#1E293B',
    bgSecondary: '#334155',
    bgTertiary: '#475569',
    textPrimary: '#F1F5F9',
    textSecondary: '#CBD5E1',
    textTertiary: '#94A3B8',
    textInverse: '#F1F5F9',
    statusSuccess: '#6C8B7D',
    statusWarning: '#FD7E14',
    statusError: '#DC3545',
    statusInfo: '#94A3B8',
    interactivePrimary: '#FD7E14',
    interactiveSecondary: '#6C8B7D',
    interactiveHover: '#FFF3CD',
    interactiveDisabled: '#475569',
    shadowColor: '#000000',
    shadowLight: 'rgba(0, 0, 0, 0.3)',
    shadowMedium: 'rgba(0, 0, 0, 0.5)',
    shadowDark: 'rgba(0, 0, 0, 0.7)',
    text: '#F1F5F9',
    tint: '#FD7E14',
    icon: '#CBD5E1',
    tabIconDefault: '#94A3B8',
    tabIconSelected: '#FD7E14',
  },
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
