import { StyleSheet } from "react-native";

import { Colors } from "@/constants/theme";

export const CUSTOMER_DETAILS = {
  firstName: "Jane",
  lastName: "Doe",
  email: "janedoe@example.com",
  phone: "08023456789",
  middleName: "-",
  address: "-",
  history: [
    {
      date: "April 7, 2025",
      time: "9:14 AM",
      agent: "John Doe",
      duration: "2m 23s",
    },
    {
      date: "March 23, 2025",
      time: "8:30 AM",
      agent: "Jane Doe",
      duration: "1m 56s",
    },
    {
      date: "March 23, 2025",
      time: "8:30 AM",
      agent: "Jane Doe",
      duration: "1m 56s",
    },
  ],
};

export const createModalStyles = (palette: (typeof Colors)["light"]) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 16,
    },
    flex: {
      flex: 1,
      justifyContent: "center",
    },
    container: {
      padding: 24,
      gap: 20,
      maxHeight: "80%",
      shadowColor: palette.shadowColor,
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: 16 },
      shadowRadius: 32,
      elevation: 6,
    },
    closeButton: {
      position: "absolute",
      zIndex: 200,
      top: 16,
      right: 16,
      width: 36,
      height: 36,
      borderRadius: 0,
      backgroundColor: palette.bgSecondary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: palette.shadowColor,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 8,
      elevation: 2,
    },
    header: {
      flexDirection: "column",
      gap: 12,
    },
    headerTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    title: {
      fontSize: 24,
      fontWeight: "700",
      color: palette.textPrimary,
    },
    offlineBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 0,
    },
    offlineBadgeText: {
      color: palette.textInverse,
      fontSize: 11,
      fontWeight: "600",
    },
    offlineMessage: {
      fontSize: 12,
      fontStyle: "italic",
    },
    form: {
      gap: 20,
    },
    footer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 4,
    },
    addFields: {
      color: palette.interactivePrimary,
      fontWeight: "600",
      fontSize: 14,
    },
    footerActions: {
      flexDirection: "row",
      gap: 16,
      alignItems: "center",
    },
    cancel: {
      color: palette.textSecondary,
      fontWeight: "600",
    },
    saveButton: {
      backgroundColor: palette.interactivePrimary,
      paddingVertical: 10,
      paddingHorizontal: 24,
      borderWidth: 1,
      borderColor: palette.interactivePrimary,
    },
    saveButtonText: {
      color: palette.textInverse,
      fontWeight: "600",
    },
    footerRight: {
      alignItems: "flex-end",
      marginTop: 16,
    },
    sendButton: {
      backgroundColor: palette.interactivePrimary,
      borderRadius: 0,
      paddingVertical: 10,
      paddingHorizontal: 24,
      borderWidth: 1,
      borderColor: palette.interactivePrimary,
    },
    sendButtonText: {
      color: palette.textInverse,
      fontWeight: "600",
    },
    headerButtons: {
      flexDirection: "row",
      gap: 12,
      alignItems: "center",
      flexWrap: "wrap",
    },
    headerAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: palette.bgSecondary,
      borderWidth: 1,
      borderColor: palette.mediumGray,
      borderRadius: 0,
    },
    headerActionText: {
      fontWeight: "600",
      color: palette.interactivePrimary,
    },
    headerActionPrimary: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 0,
      backgroundColor: palette.interactivePrimary,
      borderWidth: 1,
      borderColor: palette.interactivePrimary,
    },
    headerActionPrimaryText: {
      color: palette.textInverse,
      fontWeight: "600",
    },
    detailsContent: {
      gap: 20,
      paddingBottom: 8,
    },
    sectionCard: {
      borderRadius: 16,
      backgroundColor: palette.accentWhite,
      paddingVertical: 20,
      gap: 16,
      shadowColor: palette.shadowColor,
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 12 },
      shadowRadius: 24,
      elevation: 2,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: palette.textPrimary,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    link: {
      color: palette.interactivePrimary,
      fontWeight: "600",
    },
    detailGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 20,
    },
    historyTable: {
      backgroundColor: palette.accentWhite,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 2,
      borderRadius: 0,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: palette.mediumGray,
    },
    historyHeader: {
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
      color: palette.textSecondary,
      letterSpacing: 0.5,
      paddingHorizontal: 8,
    },
    historyCell: {
      fontSize: 13,
      color: palette.textPrimary,
      paddingVertical: 12,
      paddingHorizontal: 8,
    },
    historyLink: {
      fontSize: 13,
      fontWeight: "600",
      color: palette.interactivePrimary,
      paddingVertical: 12,
      paddingHorizontal: 8,
    },
    dateColumn: {
      flex: 1.5,
      minWidth: 140,
      paddingHorizontal: 8,
    },
    timeColumn: {
      flex: 1,
      minWidth: 100,
      paddingHorizontal: 8,
    },
    agentColumn: {
      flex: 1.5,
      minWidth: 120,
      paddingHorizontal: 8,
    },
    durationColumn: {
      flex: 1,
      minWidth: 100,
      paddingHorizontal: 8,
    },
    statusColumn: {
      flex: 1,
      minWidth: 100,
      paddingHorizontal: 8,
    },
    syncBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 6,
      paddingVertical: 4,
      borderRadius: 0,
      alignSelf: "flex-start",
    },
    syncBadgeText: {
      color: palette.textInverse,
      fontSize: 10,
      fontWeight: "600",
    },
    actionColumn: {
      flex: 1.2,
      minWidth: 120,
      paddingHorizontal: 8,
    },
    twoColumn: {
      flexDirection: "row",
      gap: 16,
      width: "100%",
    },
    twoColumnInner: {
      flex: 1,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "90%",
      maxWidth: 400,
      maxHeight: "80%",
      borderRadius: 0,
      overflow: "hidden",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: palette.mediumGray,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "600",
    },
    modalCloseButton: {
      width: 32,
      height: 32,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 0,
    },
    modalList: {
      maxHeight: 400,
    },
    modalOption: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.mediumGray,
    },
    modalOptionText: {
      fontSize: 14,
      flex: 1,
    },
    datePickerModal: {
      width: "90%",
      maxWidth: 400,
      borderRadius: 0,
      overflow: "hidden",
    },
    datePicker: {
      width: "100%",
    },
    datePickerFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: palette.mediumGray,
    },
    datePickerButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 0,
      borderWidth: 1,
      borderColor: palette.mediumGray,
      backgroundColor: palette.accentWhite,
    },
    datePickerButtonText: {
      fontSize: 14,
      fontWeight: "600",
    },
  });

export const createDetailStyles = (palette: (typeof Colors)["light"]) =>
  StyleSheet.create({
    item: {
      width: "48%",
      gap: 6,
    },
    label: {
      fontSize: 13,
      color: palette.primaryLighter,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    value: {
      fontSize: 15,
      fontWeight: "600",
      color: palette.textPrimary,
    },
  });
